### ISSUE TITLE
Cleaning manuscript

### ISSUE THREAD

**Issue by ajacobs71** [macartan/integrated_inferences#65]
- [x] Make sure each author has their entry in the same way everywhere in the bibliography.
- [x] Make sure all chapter, figure, and table cross-references are working
- [x] Replace instances of "one" with "we" 
- [x] Search for "1(" and turn into an indicator function
- [x] Search for tables that are too wide, put them on their own page, rotated 90 degrees

**Comment by macartan** [comment]
* Full read though: spelling check
* Full read though: flag unfinished text
* Fix any hardcoded bib entries
* check latex headers on table
* check consistent notation usage: especially around, theta, q, Q
* turn do_diagnosis to true and re run all analyses; make sure no old items in saved being used (one approach is to empty the saved folder and then try to recreate everything; figure out what is missing)
* rename all .rds outputs to have a consistent name format
* check all library calls and functions are in _use_pacakges.R
* make sure everything makes sense and flag if not!
* check ggdag spacing to optimize further where possible

**Comment by jonfoong** [comment]
do_diagnosis issues:
1. chapter 9 chunk 8: object updated not found; chunks 11 & 12 not shown and the text looks incomplete
2. chapter 11 chunk 25 'multilevel_dirichlet.stan' not found. 
3. 3. chapter 13 errors in chunks 6 and 9

**Comment by macartan** [comment]
On Tue, Nov 30, 2021 at 7:01 PM jonfoong ***@***.***> wrote:

> do_diagnosis issues:
>
>    1. chapter 9 chunk 8: object updated not found; chunks 11 & 12 not
>    shown and the text looks incomplete
>
> code to generate "updated" is here

Chapter 6 Basic Models | Causal Models: Guide to CausalQueries
(macartan.github.io)
<https://macartan.github.io/causalmodels/applications.html#the-ladder-of-causation-in-an-x-rightarrow-y-model>

which part of the text is incomplete?

<https://macartan.github.io/causalmodels/applications.html#the-ladder-of-causation-in-an-x-rightarrow-y-model>

>
>    1. chapter 11 chunk 25 'multilevel_dirichlet.stan' not found.
>
>
I share a db link to this file and related


>    1.
>       1. chapter 13 errors in chunks 6 and 9
>
>
what are the names of those chunk?

Note that sims for 13 and 14 are generated extenrally so we should create
replication scripts; sharing now

THANKS

**Comment by jonfoong** [comment]
Incomplete text chapter 9:

![image](https://user-images.githubusercontent.com/59555900/144206110-433d4227-e71d-41d0-b4e7-3ed1f7ebea4e.png)

I assume you want the code chunks (unnamed, chunks 11 and 12) to be shown? Also, the following para "We see that the model performs well" I'm assuming you're referring to table 9.8? Formatting has pushed 9.8 to below the para so you might want to make an explicit reference to 9.8 instead

Chapter 13 chunks:
chunk 6: illustration
chunk 9: test

**Comment by jonfoong** [comment]
Ok the errors in chunks 6 and 9 are due to problems with CQtools functions, I'm using ver 0.0.2
